@startuml recipeManagement
left to right direction
(Create recipe) as createR
(Update recipe) as updateR
(Delete recipe) as deleteR

user --> createR
user --> updateR
user --> deleteR
@enduml

@startuml ingredientManagement
left to right direction
(Create ingredient) as createI
(Update ingredient) as updateI
(Delete ingredient) as deleteI

user --> createI
user --> updateI
user --> deleteI
@enduml

@startuml categoryManagement

left to right direction

actor Admin


Admin --> (Manage Categories)
(Manage Categories) --> (Add Categorie)
(Manage Categories) --> (Update Categorie)
(Manage Categories) --> (Delete Categorie)

@enduml

@startuml adManagement

left to right direction

actor Admin


Admin --> (Manage Averts)
(Manage Averts) --> (Add Avert)
(Manage Averts) --> (Update Avert)
(Manage Averts) --> (Delete Avert)

@enduml

@startuml adminUserManagement

left to right direction

actor Admin

Admin --> (User management)
(User management) --> (log in)
(User management) --> (log out)
(User management) --> (maintain admin information)
(User management) --> (maintain user information)

@enduml

@startuml userUserManagement

left to right direction

actor User

User --> (User management)
(User management) --> (log in)
(User management) --> (log out)
(User management) --> (register)
(User management) --> (maintain user information)

@enduml

@startuml newsManagement

left to right direction

actor Admin

Admin --> (News management)
(News management) --> (add a news)
(News management) --> (update a news)
(News management) --> (display a news)

@enduml

@startuml suggestionManagement

left to right direction

actor User
actor Admin

Admin -|> User

Admin --> (1. Manage Suggestions)
User --> (2. Manage Suggestions)
(2. Manage Suggestions) --> (Add Suggestion)
(1. Manage Suggestions) --> (Update Suggestion)
(1. Manage Suggestions) --> (Delete Suggestion)
(1. Manage Suggestions) --> (Read Suggestion)
@enduml

@startuml commentManagement

left to right direction

actor User as u
actor Admin as a
u <|- a

usecase (Comment a recipe) as u2
usecase (Rate a recipe) as u1
usecase (Delete a Comment) as u3
usecase (Name the Comment) as u4

u --> u1
a --> u3
u2 .> u4 : <<include>>
u2 .u.> u1 : <<extends>>
@enduml

@startuml calendarManagement

left to right direction

actor User as u

usecase (Add to calendar) as u1
usecase (Select a date & a meal) as u2
usecase (See calendar) as u3
usecase (Delete from calendar) as u4

u --> u1
u --> u3
u --> u4
u1 ..> u2 : <<include>>

@enduml

@startuml partnerManagement

left to right direction
actor "User" as user
actor "Administrator" as admin

user --> (View Partner Details 1)
admin -l-|> user

admin --> (View Partner Details 2)
(View Partner Details 2) ..> (Remove Partner): <<extends>>
(View Partner Details 2) ..> (Edit Partner): <<extends>>
(View Partner Details 2) ..> (Add Partner): <<extends>>


@enduml

@startuml recipeListManagement

left to right direction

actor "User" as user
actor "Administrator" as admin

admin --|> (user)
(View Recipe Lists) ..> (Recipe List): <<extends>>
(View Recipe Lists) --> (Remove Recipe Lists)
(View Recipe Lists) --> (Add Recipe Lists)
user --> (View Recipe Lists)

(Recipe List) --> (View Recipes)
(Recipe List) --> (Add Recipes to Cart)
(Recipe List) --> (Remove Recipes)
@enduml

@startuml cartManagement

left to right direction

actor "User" as user
actor "Administrator" as admin

admin --|> user
user -->(View Cart)
user --> (Add to Cart)

(View Cart) <.l. (Validate Cart): <<extends>>
(View Cart) <.. (Remove from Cart) : <<extends>>
(View Cart) <.. (Edit Cart) : <<extends>>
(View Cart) <.. (Empty Cart) : <<extends>>


@enduml