@startuml loginClassDiagram
hide empty members
class LoginWindow {
  + display()
}

class LoginController {
  + login()
}

Interface DAO {
  + {abstract} login()
  + {abstract} validatePassword()
}

class AuthSystem {
  + login()
  + validatePassword()
}

class ConnectionManager {
  # {static} pool: DataSource
  + {static} getConnection(): Connection
  + {static} releaseConnection(): void
}

abstract DAOFactory {
  - instance: DAOFactory
  - DAOFactory()
  + getInstance(): DAOFactory
}
DAOFactory *-- DAOFactory

class AuthSysFactory
AuthSysFactory -u-|> DAOFactory


database "Postgres\nDatabase" as Postgres {

}

DAO               -u-> ConnectionManager
AuthSystem        .u.|> DAO
LoginController   -->  DAO
LoginWindow       -> LoginController
ConnectionManager -d-> Postgres
AuthSysFactory    -d-> AuthSystem: <<instanciate>>
@enduml