@startuml loginSequence
skinparam responseMessageBelowArrow true

actor User
participant LoginPage
participant LoginController
participant UserFacade
participant AbstractFactory
participant UserDAO
participant DataBase

activate User
' activate DataBase

User -> LoginPage++: enterUsername
User -> LoginPage: enterPassword
User -> LoginPage: clickOnLogin
LoginPage -> LoginController++: onClickButtonLogin()
LoginController -> UserFacade++: getUserFacade()
UserFacade -> AbstractFactory++: getUserDAO():
return UserDAO
return UserFacade
LoginController -> UserFacade++ : login():
UserFacade -> UserDAO++: getUserbyIDPwd():
return Optional<User>
return Optional<User>

alt User is notNull
    LoginController --> LoginPage: setScene("home")
    LoginPage --> User--: display(homeWindow)
else User is Null
    LoginController -> LoginPage: setText("Wrong username or password")
    LoginPage --> User--: display(invalid)
end

@enduml