@startuml loginSequence
skinparam responseMessageBelowArrow true

actor User
participant Main
participant LoginController
participant UserFacade
participant AbstractFactory
participant UserDAO
participant DataBase

activate User
' activate DataBase

User -> Main++: enterUsername
User -> Main: enterPassword
User -> Main: clickOnLogin
Main -> LoginController++: onClickButtonLogin()
LoginController -> UserFacade++: login():User|Null
UserFacade -> AbstractFactory++: getUserDAO():UserDAO
UserFacade -> UserDAO++: getUserbyIDPwd():User|Null

alt User is notNull
    LoginController --> Main: setScene("home")
    Main --> User--: display(homeWindow)
else User is Null
    LoginController -> Main: setText("Wrong username or password")
    Main --> User--: display(invalid)
end

@enduml