@startuml packageDiagram
hide empty members
package  controller{
  class LoginController
}

package dao{
  class PostgresUserDAO
  interface UserDAO
}

package dbutils{
  class ConnectionManager
}

package facade{
  class UserFacade
}

package factory{
  interface AbstractFactory
  class PostgresFactory
}

package model{
  class User
}

package view{
  class Login
}
controller --[hidden]d-- dao
facade --[hidden]d-- view
dao --[hidden]d-- factory
view --[hidden]d-- model

@enduml