@startuml SuggestionsUser
hide empty members

class Suggestion {
    +int id
    +String title
    +String description
    +int authorId
    +String category
}

class SuggestionPage {
    + Suggestion suggestion
    + OnClickSendSuggestion()
    + OnClickCancel()
}

class SuggestionController {
    + SuggestionController()
    + OnClickSendSuggestion()
}

class SuggestionFacade {
    + SuggestionDAO suggestionDAO
    + SuggestionFacade()
    + SendSuggestion()
    + UpdateSuggestion()
    + DeleteSuggestion()
}

interface AbstractFactory {
    + GetSuggestionDAO()
}

class PostgresFactory {
    + GetSuggestionDAO()
}

class SuggestionDAO {
    + SuggestionDAO()
    + CreateSuggestion()
    + GetSuggestion()
    + GetSuggestions()
    + UpdateSuggestion()
    + DeleteSuggestion()
}

class SuggestionPanelPage {
    + Suggestion[] suggestions
    + ViewSuggestionDetails()
    + DeleteSuggestion()
}

class SuggestionPanelController {
    + SuggestionPanelController()
    + ViewSuggestionDetails()
    + DeleteSuggestion()
}

Suggestion <-- SuggestionPage
AbstractFactory <|-- PostgresFactory
SuggestionFacade --> AbstractFactory
PostgresFactory *-- SuggestionDAO
SuggestionPage --> SuggestionController
SuggestionController --> SuggestionFacade
SuggestionFacade .. SuggestionDAO
Suggestion <-- SuggestionPanelPage
SuggestionPanelPage --> SuggestionPanelController
SuggestionPanelController --> SuggestionFacade

@enduml