@startuml IngredientClassDiagram
hide empty members

class Main {
  + main()
}

class IngredientController {
  + display()
  + showList()
  + showForm()
  + onClickCreateIngredient()
  + onClickDeleteIngredient()
  + onClickUpdateIngredient()
}


class IngredientFacade {
  + createIngredient()
  + updateIngredient()
  + deleteIngredient()
}


interface IngredientAbstractFactory {
  + {abstract} getIngredientDAO() : IngredientDAO

}


class PostgresIngredientFactory {
  + getPostgresIngredientFactory(): PostgresIngredientFactory
  + get IngredientDAO() : IngredientDAO
}


Interface IngredientDAO {
  + {abstract} createIngredient()
  + {abstract} updateIngredient()
  + {abstract} deleteIngredient()
}


class PostgresIngredientDAO{
  + getPostgresIngredientDAO() : IngredientDAO
  + createIngredient()
  + updateIngredient()
  + deleteIngredient()
}


class ConnectionManager {
  - {static} PGConnectionPoolDataSource: DataSource
  + {static} openConnectionPool(): void
  + {static} getConnection(): Connection
  + {static} closeConnectionPool(): void
}

PostgresIngredientFactory -u-|> IngredientAbstractFactory
PostgresIngredientDAO     -l-|> IngredientDAO

Main            "1" -r-> "1" IngredientController: <  controls
IngredientController      "1" -r-> "1" IngredientFacade: > interact with
IngredientFacade          "1" --> "1" IngredientAbstractFactory: > uses
PostgresIngredientFactory "1" --> "1" PostgresIngredientDAO: > create
PostgresIngredientDAO     "1" --> "1" ConnectionManager:> get connection from
@enduml