@startuml UpdateIngredient
skinparam responseMessageBelowArrow true

actor User
participant IngredientPage
participant IngredientController
participant IngredientFacade
participant AbstractFactory
participant IngredientDAO
participant DataBase

activate User

User -> IngredientPage++ : changeInformations
User -> IngredientPage : clickOnUpdate

IngredientPage -> IngredientController++ : updateIngredient()

IngredientController -> IngredientFacade++ : updateIngredient()

IngredientFacade -> AbstractFactory++ : getIngredientDAO(): IngredientDAO
return ingredientDAO
IngredientFacade -> IngredientDAO++ : updateIngredient()
IngredientDAO -> IngredientDAO : ingredientAlreadyExist() : boolean
return boolean
return boolean

alt return True
  IngredientController -> IngredientPage : Notification("Success")

  IngredientPage -> User : display("L'ingrédient a été mis à jour")

else return False
  IngredientController -> IngredientPage : Notification("Failed")

  IngredientPage -> User : display("L'ingrédient existe déjà")

else return Error
IngredientController -> IngredientPage : Notification("Error")

IngredientPage -> User : display("Erreur")
end

@enduml