@startuml <Update Cart>
skinparam responseMessageBelowArrow true

actor User
participant View.Main
participant CartController
participant CartFacade
participant AbstractFactory
participant CartDAO
participant DataBase

activate User

User -> View.Main++: editQuantity
User -> View.Main: onClickButtonEditCart()
View.Main -> CartController++: updateCart()
CartController -> CartFacade++: updateCart()
CartFacade -> AbstractFactory++: getCartDAO()
return CartDAO
CartFacade -> CartDAO++: updateCart()
return
return
CartController --> View.Main: updateSucessful()
View.Main --> User: display(CartListWindow)

@enduml

== small ==

@startuml <Validate Cart>
skinparam responseMessageBelowArrow true

actor User
participant View.Main
participant CartController
participant CartFacade
participant AbstractFactory
participant CartDAO
participant DataBase

activate User

User -> View.Main++: onClickButtonValidateCart()
View.Main -> CartController++: validateCart()
CartController -> CartFacade++: validateCart()
CartFacade -> AbstractFactory++: getCartDAO()
return CartDAO
CartFacade -> CartDAO++: validateCart()
return
return
CartController --> View.Main: validateSucessful()
View.Main --> User: display(CartListWindow)

@enduml

== small ==

@startuml <Add To Cart>
skinparam responseMessageBelowArrow true

actor User
participant View.Main
participant CartController
participant CartFacade
participant AbstractFactory
participant CartDAO
participant DataBase

activate User

User -> View.Main++: selectRecipe
User -> View.Main: onClickButtonAddToCart()
View.Main -> CartController++: addToCart()
CartController -> CartFacade++: addToCart()
CartFacade -> AbstractFactory++: getCartDAO()
return CartDAO
CartFacade -> CartDAO++: addToCart()
return
return
CartController --> View.Main: addSucessful()
View.Main --> User: display(CartListWindow)

@enduml

== small ==

@startuml <Empty Cart>
skinparam responseMessageBelowArrow true

actor User
participant View.Main
participant CartController
participant CartFacade
participant AbstractFactory
participant CartDAO
participant DataBase

activate User

User -> View.Main++: onClickButtonEmptyCart()
View.Main -> CartController++: emptyCart()
CartController -> CartFacade++: emptyCart()
CartFacade -> AbstractFactory++: getCartDAO()
return CartDAO
CartFacade -> CartDAO++: emptyCart()
return
return

CartController --> View.Main: emptySucessful()
View.Main --> User: display(CartListWindow)

@enduml
