@startuml model
hide empty members
' skinparam Linetype polyline

class ingredientCategory {
  {field} id => serial
  {field} name => varchar(255)
}

class recipeCategory {
  {field} id => serial
  {field} name => varchar(255)
}

class suggestionCategory {
  {field} id => serial
  {field} name => varchar(255)
}

class mealCategory {
  {field} id => serial
  {field} name => varchar(255)
}

class ingredient {
  {field} id => serial
  {field} name => varchar(255)
  {field} allergen => boolean
}

class recipe {
  {field} id => serial
  {field} name => varchar(255)
  {field} summary => varchar(500)
  {field} description => text
  {field} image => blob
  {field} nbPerson => float
  {field} /rating => float
}


class advert {
  {field} promotion => text
  {field} price => float
}

class suggestion {
  {field} id => serial
  {field} title => varchar(255)
  {field} description => text
}


class comment {
  {field} rating => float
  {field} content => text
  {field} date => date
}

class calendar

class calendar_day {
  {field} date => date
}


class recipeList {
  {field} name => varchar(255)
}

class cart {
}

class cart_entry {
  quantity => float
}

class partner {
  {field} id => serial
  {field} name => varchar(255)
  {field} description => text
  {field} website => varchar(255)
}

class news {
  {field} id => serial
  {field} title => varchar(255)
  {field} content => text
  {field} date => date
  {field} photo => blob
}

class user {
  {field} id => serial
  {field} name => varchar(255)
  {field} email => varchar(255)
  {field} password => varchar(255)
  {field} phone => varchar(32)
  {field} birthdate => date
  {field} question => varchar(255)
  {field} answer => varchar(255)
  {field} isAdmin => boolean
}

class quantity {
  {field} quantity => int
}

user "1"          -- "1" cart: > owns
calendar "1" -- "*" calendar_day: > contains

advert "*"        -u- "1" ingredient: > is about
user "*"          -- "*" ingredient: > is allergic to

advert "*"        -- "1" partner: > is from

comment "*"       -- "1" recipe: > is about
recipeList "*"    -- "*" recipe: > has
suggestion "*"    -u- "1" recipe: > is about

cart "*"             -- "*" ingredient: > contains
(recipe, ingredient) .. quantity
recipe "*"           -- "*" ingredient: > contains
(cart, ingredient)   .. cart_entry
calendar_day "*"     -- "*" recipe: > is on
(calendar_day, recipe)   .. mealCategory

calendar "1"      -u- "1" user: < owns
recipeList "*"    -u- "1" user: > owns
comment "*"       -u- "1" user: > is from
news "*"          -- "1" user: > is from

ingredient "*"    -- "*" ingredientCategory: > is
recipe "*"        -- "*" recipeCategory: > is
suggestion "*"    -d- "1" suggestionCategory: > is
@enduml