@startuml model
' hide empty members
' skinparam Linetype polyline

class ingredientCategory {

  {field} name => varchar(255)
}

class recipeCategory {

  {field} name => varchar(255)
}

class suggestionCategory {

  {field} name => varchar(255)
}

class mealCategory {

  {field} name => varchar(255)
}

class ingredient {

  {field} name => varchar(255)
  {field} allergen => boolean
}

class recipe {

  {field} name => varchar(255)
  {field} summary => varchar(500)
  {field} description => text
  {field} image => blob
  {field} nbPerson => float
  {field} /rating => float
}


class advert {
  {field} promotion => text
  {field} price => float
}

class suggestion {

  {field} title => varchar(255)
  {field} description => text
}


class comment {
  {field} rating => float
  {field} content => text
  {field} date => date
}

class calendar

class calendar_day {
  {field} date => date
}


class recipeList {
  {field} name => varchar(255)
}

class cart {
}

class cart_entry {
  quantity => float
}

class partner {

  {field} name => varchar(255)
  {field} description => text
  {field} website => varchar(255)
}

class news {

  {field} title => varchar(255)
  {field} content => text
  {field} date => date
  {field} photo => blob
}

class user {

  {field} name => varchar(255)
  {field} email => varchar(255)
  {field} password => varchar(255)
  {field} phone => varchar(32)
  {field} birthdate => date
  {field} question => varchar(255)
  {field} answer => varchar(255)
  {field} isAdmin => boolean
}

class quantity {
  {field} quantity => int
}

user "1"          -- "1" cart
calendar "1" --> "*" calendar_day

advert "*"        -u- "1" ingredient
user "*"          -- "*" ingredient

advert "*"        -- "1" partner

comment "*"       -- "1" recipe
recipeList "*"    -- "*" recipe
suggestion "*"    -u- "1" recipe

cart "*"             -- "*" ingredient
' TODO : ajouter les chiffres pour la liaison
(recipe, ingredient) .. quantity
recipe "*"           -- "*" ingredient
(cart, ingredient)   .. cart_entry
calendar_day "*"     -- "*" recipe
(calendar_day, recipe)   .. mealCategory

' ! virer le ": < owns" transforme le diagramme un peu n'importe comment
calendar "1"      -u- "1" user: < owns
recipeList "*"    -u- "1" user
' ? a voir si on garde ou pas
' comment "1"       -u-> "1" user

ingredient "*"    -- "*" ingredientCategory
recipe "*"        -- "*" recipeCategory
suggestion "*"    -d- "1" suggestionCategory
@enduml