@startuml recipeClassDiagram
hide empty members

class RecipePage {
  + display()
}

class RecipeController {
  + showList()
  + showForm()
  + onClickCreateRecipe()
  + onClickDeleteRecipe()
  + onClickUpdateRecipe()
}


class RecipeFacade {
  + createRecipe()
  + updateRecipe()
  + deleteRecipe()
}


interface RecipeAbstractFactory {
  + {abstract} getRecipeDAO() : RecipeDAO

}


class PostgresRecipeFactory {
  + getPostgresRecipeFactory(): PostgresRecipeFactory
  + get RecipeDAO() : RecipeDAO
}


Interface RecipeDAO {
  + {abstract} createRecipe()
  + {abstract} updateRecipe()
  + {abstract} deleteRecipe()
}


class PostgresRecipeDAO{
  + getPostgresRecipeDAO() : RecipeDAO
  + createRecipe()
  + updateRecipe()
  + deleteRecipe()
}


class ConnectionManager {
  - {static} PGConnectionPoolDataSource: DataSource
  + {static} openConnectionPool(): void
  + {static} getConnection(): Connection
  + {static} closeConnectionPool(): void
}


PostgresRecipeFactory -u-|> RecipeAbstractFactory
PostgresRecipeDAO     -l-|> RecipeDAO

RecipePage            -r-> RecipeController: <  controls
RecipeController      -r-> RecipeFacade: > interact with
RecipeFacade          --> RecipeAbstractFactory: > uses
PostgresRecipeFactory --> PostgresRecipeDAO: > create
PostgresRecipeDAO     --> ConnectionManager: > get connection from



@enduml