@startuml CreateRecipe
skinparam responseMessageBelowArrow true

actor User
participant RecipePage
participant RecipeController
participant RecipeFacade
participant RecipeAbstractFactory
participant RecipeDAO
participant DataBase

activate User
activate DataBase

User -> RecipePage++ : changeInformations
User -> RecipePage : clickOnUpdate

RecipePage -> RecipeController++ : updateRecipe()

RecipeController -> RecipeFacade++ : updateRecipe(): True|Error

RecipeFacade -> RecipeAbstractFactory++ : getRecipeDAO(): RecipeDAO
RecipeFacade -> RecipeDAO++ : updateRecipe(): True|Error

alt return True
  RecipeController -> RecipePage : updateSuccessful()

  RecipePage -> User : display("La recette a été mis à jour")

else return Error
  RecipeController -> RecipePage : updateFailed()

  RecipePage -> User : display(Error)
end

@enduml