@startuml UpdateRecipe
skinparam responseMessageBelowArrow true

actor User
participant RecipePage
participant RecipeAdminController
participant RecipeFacade
participant RecipeAbstractFactory
participant RecipeDAO
participant DataBase

activate User

User -> RecipePage++ : changeInformations
User -> RecipePage : clickOnUpdate

RecipePage -> RecipeAdminController++ : updateRecipe()

RecipeAdminController -> RecipeFacade++ : updateRecipe()

RecipeFacade -> RecipeAbstractFactory++ : getRecipeDAO(): RecipeDAO
return recipeDAO
RecipeFacade -> RecipeDAO++ : updateRecipe()
return
return

alt return no errors
  RecipeAdminController -> RecipePage : Notification("Success")

  RecipePage -> User : display("La recette a été mise à jour")

else return Error
  RecipeAdminController -> RecipePage : Notification("Failed")

  RecipePage -> User : display(Error)
end

@enduml