@startuml UpdateRecipe
skinparam responseMessageBelowArrow true

actor User
participant RecipePage
participant RecipeController
participant RecipeFacade
participant RecipeAbstractFactory
participant RecipeDAO
participant DataBase

activate User
' activate DataBase

User -> RecipePage++ : changeInformations
User -> RecipePage : clickOnUpdate

RecipePage -> RecipeController++ : updateRecipe()

' same remarks as or updateingredientSequence
RecipeController -> RecipeFacade++ : updateRecipe()

RecipeFacade -> RecipeAbstractFactory++ : getRecipeDAO(): RecipeDAO
return recipeDAO
RecipeFacade -> RecipeDAO++ : updateRecipe()
return
return

alt return no errors
  RecipeController -> RecipePage : updateSuccessful()

  RecipePage -> User : display("La recette a été mise à jour")

else return Error
  RecipeController -> RecipePage : updateFailed()

  RecipePage -> User : display(Error)
end

@enduml